export const addTodo = "ADD_TODO"
export const setVisibilityFilter = "SET_VISIBILITY_FILTER"
export const toggleTodo = "TOGGLE_TODO"
export const editTodo = "EDIT_TODO"
export const delTodo = "DELETE_TODO"